
# URL of Acronis DC with API version
@baseUrl = https://dev-cloud.acronis.com/api/2
###

# Issue a JST token uning an API Client credentials
# @name issueToken
POST {{baseUrl}}/idp/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}}:{{client_secret}}

grant_type=client_credentials

###
@token = {{issueToken.response.body.access_token}}

# Get an API Client info
# @name apiClient
GET {{baseUrl}}/clients/{{client_id}} HTTP/1.1
Authorization: Bearer {{token}}

###
# Save an API Client tenant id into the @root_tenant_id variable
@root_tenant_id = {{apiClient.response.body.tenant_id}}

###

# Get a root teanant info
GET {{baseUrl}}/tenants/{{root_tenant_id}} HTTP/1.1
Authorization: Bearer {{token}}

###

# Create a partner tenant
# @name partner
POST {{baseUrl}}/tenants HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Partner {{$guid}}",
    "kind": "partner",
    "parent_id": "{{root_tenant_id}}"
}

###
@partner_tenant_id = {{partner.response.body.id}}
###

# Create a customer tenant
# @name customer
POST {{baseUrl}}/tenants HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Customer {{$guid}}",
    "kind": "customer",
    "parent_id": "{{partner_tenant_id}}"
}

###
@customer_tenant_id = {{customer.response.body.id}}
###

# Get availiable offering items for a partner
# @name oiAvailibleForPartner
GET {{baseUrl}}/tenants/{{root_tenant_id}}/offering_items/available_for_child?edition=pck_per_workload&kind=partner HTTP/1.1
Authorization: Bearer {{token}}

###
@ois = {{oiAvailibleForPartner.response.body.items}}
###

# Set offering items for a partner
PUT {{baseUrl}}/tenants/{{partner_tenant_id}}/offering_items 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "offering_items": {{ois}} 
}

###

# Get availiable offering items for a customer
# @name oiAvailibleForCustomer
GET {{baseUrl}}/tenants/{{partner_tenant_id}}/offering_items/available_for_child?edition=pck_per_workload&kind=customer HTTP/1.1
Authorization: Bearer {{token}}

###
@ois = {{oiAvailibleForCustomer.response.body.items}}
###

# Set offering items for a customer
PUT {{baseUrl}}/tenants/{{customer_tenant_id}}/offering_items 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "offering_items": {{ois}} 
}
